# Generated by Django 4.1.3 on 2023-02-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=44, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone')),
                ('responsible_name', models.CharField(max_length=44, verbose_name='Nome do responsável')),
                ('coordenadoria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordenadoria')),
                ('demand', models.TextField(verbose_name='Sobre a demanda')),
                ('demand_type', models.CharField(max_length=255, verbose_name='Tipo de demanda')),
                ('approx_release_date', models.DateTimeField(auto_now=True, verbose_name='Data aproximada de lançamento')),
                ('target_users', models.CharField(max_length=255, verbose_name='Principais usuários')),
                ('approx_quantity_users', models.PositiveIntegerField(verbose_name='Quantidade aproximada de usuários')),
                ('users_actions', models.TextField(verbose_name='Ações do sistema')),
                ('external_factors', models.TextField(verbose_name='Fatores externos que continuam impactando o usuário')),
                ('functionalities', models.TextField(verbose_name='Funcionalidades')),
                ('register_datetime', models.DateTimeField(auto_now=True, verbose_name='Data de registro')),
            ],
            options={
                'verbose_name': 'solicitação de projeto',
                'verbose_name_plural': 'solicitações de projeto',
            },
        ),
    ]
