# Generated by Django 4.1.3 on 2023-01-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=55, verbose_name='tag id')),
                ('title', models.TextField(verbose_name='título')),
                ('body', models.TextField(verbose_name='corpo')),
                ('creation_datetime', models.DateTimeField(auto_now=True, verbose_name='data de criação')),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='última atualização')),
            ],
            options={
                'verbose_name': 'seção',
                'verbose_name_plural': 'seções',
            },
        ),
    ]
