# Generated by Django 4.1.3 on 2023-01-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='landing_page/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='section',
            name='tag_id',
            field=models.CharField(max_length=255, verbose_name='tag id'),
        ),
    ]
