# Generated by Django 4.1.3 on 2023-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=44, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('coordenadoria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordenadoria')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('register_datetime', models.DateTimeField(auto_now=True, verbose_name='Data de registro')),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
            },
        ),
    ]
